export enum ErrorCode {
  // Auth
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',

  // Users
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EMAIL_TAKEN = 'USER_EMAIL_TAKEN',
  USER_PROTECTED = 'USER_PROTECTED',
  ROLE_WEIGHT_EXCEEDED = 'ROLE_WEIGHT_EXCEEDED',

  // Roles
  ROLE_NOT_FOUND = 'ROLE_NOT_FOUND',
  ROLE_NAME_TAKEN = 'ROLE_NAME_TAKEN',
  ROLE_PROTECTED = 'ROLE_PROTECTED',

  // Permissions
  PERMISSION_NOT_FOUND = 'PERMISSION_NOT_FOUND',

  // Generic
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
